// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VirtualQueueSystem.Data;

#nullable disable

namespace VirtualQueueSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250204023730_SeedMenuItems")]
    partial class SeedMenuItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("Queue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("JoinTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Queues");
                });

            modelBuilder.Entity("Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReservationTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("VirtualQueueSystem.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Breakfast",
                            ImageUrl = "/images/pancakes.jpg",
                            Name = "Pancakes",
                            Price = 5.99m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Breakfast",
                            ImageUrl = "/images/omelette.jpg",
                            Name = "Omelette",
                            Price = 4.50m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Lunch",
                            ImageUrl = "/images/grilled-chicken.jpg",
                            Name = "Grilled Chicken",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Lunch",
                            ImageUrl = "/images/caesar-salad.jpg",
                            Name = "Caesar Salad",
                            Price = 6.50m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Dinner",
                            ImageUrl = "/images/steak.jpg",
                            Name = "Steak",
                            Price = 14.99m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Dinner",
                            ImageUrl = "/images/salmon.jpg",
                            Name = "Salmon",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Snacks",
                            ImageUrl = "/images/fries.jpg",
                            Name = "French Fries",
                            Price = 3.99m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Snacks",
                            ImageUrl = "/images/nuggets.jpg",
                            Name = "Chicken Nuggets",
                            Price = 4.99m
                        });
                });

            modelBuilder.Entity("VirtualQueueSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
